### PR TITLE
Move GetStartOnSystemStartup and SetStartOnSystemStartup to GUI code

### PR DESCRIPTION
**Pull request by IngCr3at1on**
Reference: https://github.com/bitcoin/bitcoin/pull/1178

### CODE REVIEW

**Comment by mitchellcash** [comment]
Again I'll confirm Windows builds and running the wallet

**Comment by IngCr3at1on** [comment]
This has been rebased over master @mitchellcash if you have already tested this please test it again.

**Comment by mitchellcash** [comment]
Sorry I missed testing this before it conflicted again. I will await your next rebase over master and will make this the next thing I test.

**Comment by IngCr3at1on** [comment]
@mitchellcash I hadn't even noticed it was broken lol. Rebased over master to accommodate #391

**Comment by mitchellcash** [comment]
Like the Bitcoin commit it seems that shlwapi.h can be removed from util.cpp after your changes.

**Comment by IngCr3at1on** [comment]
removed and tested (15 minutes)

**Comment by mitchellcash** [comment]
Looks good to me from here.

**Comment by IngCr3at1on** [comment]
squashed and confirmed gitian builds (50 minutes)

**Pull request merged**
