### PR TITLE
Update minimum protocol for phase 2 primenodes

### PR DESCRIPTION
**Pull request by IngCr3at1on**

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
This will update the minimum protocol on September 1st 12:00:00 GMT

I've asked @mitchellcash to confirm these before they're merged to make sure I haven't missed anything.

**Comment by IngCr3at1on** [comment]
Updated timestamp to be September 15th instead of the 1st.

**Comment by PaycoinMaster** [comment]
Waiting on @mitchellcash Please confirm

**Comment by jwrb** [comment]
@PaycoinMaster This looks good! LGTM :+1:

**Comment by mitchellcash** [comment]
Thanks @jwrb. Sorry I didn't get a chance to test my work job has been crazy lately and haven't had the time!

**Pull request merged**
