### PR TITLE
RPC: Forbid RPC username == RPC password

### PR DESCRIPTION
**Pull request by jwrb**
Added security measure taken from [#1987](https://github.com/bitcoin/bitcoin/pull/1987)

Compiles & Runs as expected

### CODE REVIEW

**Comment by mitchellcash** [comment]
Me being lazy when I've tested Paycoin in the past I've used:
```
rpcuser=test
rpcpassword=test
```

Guess I'm going to have to change that :P

**Comment by jwrb** [comment]
Yeah, security though. Some servers out there could be using this so it's best to at least try and secure them.

**Comment by mitchellcash** [comment]
Yeah agreed, I'm all for security improvements and every bit counts, LGTM.

**Comment by IngCr3at1on** [comment]
I agree with @mitchellcash LGTM

**Pull request merged**
