### PR TITLE
Fix regression introduced in 0b47971c918a8efadcc477e3bd16566df5957e7d

### LINKED ISSUE #405: Invalid PrimeNode Key
On the testnet using the latest master to build it seems that it is no longer correctly initiliasing using a what is a correct PrimeNode key upon a clean launch.

To reproduce:
1. Clean out the testnet3 folder apart from wallet.dat
2. In paycoin.conf ensure you are using `testnet=1` and a correct `primenodekey`
3. Will throw an error `initPrimeNode() : invalid primenode key`

If you are working from a past build in which it did allow you to use a PrimeNode key then you won't experience this issue using the latest master for whatever reason. It is only when you clean out the data directory that it starts causing this error.

### PR DESCRIPTION
**Pull request by mitchellcash**
Fixes #405.

### CODE REVIEW

**Comment by jwrb** [comment]
Looks good. @IngCr3at1on Could you take a look and verify this?

**Comment by mitchellcash** [comment]
@jwrb sorry you don't need a prime key to test this. My issue was discovered because my prime key wasn't working on the testnet so with no investigation I posted my issue but then you will see I talk myself to a different conclusion about what is happening lol

To test this:
1. Build the latest master branch and try to run the wallet on the testnet - it won't work.
2. Now build this branch and run the wallet on the testnet - it will work.

That's about the extent of the testing needed. In any event I private messaged you a testnet prime key so you can muck around with it in testing etc.

**Comment by jwrb** [comment]
Looks good then! LGTM! :+1:

**Comment by IngCr3at1on** [comment]
This doesn't break command line RPC on the testnet? (which is why that setting was set where it was)?

**Comment by jwrb** [comment]
I think I'd actually prefer to use #386 here

**Comment by IngCr3at1on** [comment]
@jwrb I was just trying to confirm this was the same issue, though I'm pretty sure it is.

**Comment by mitchellcash** [comment]
You are correct, I did only perform testing on the Qt wallet. The reason I chose my change was that it was closer to how the Bitcoin code base worked (at a a certain point in time). There will probably be disagreement over this but I try as much as I can to aim towards what Bitcoin is doing making it easier to use ideas they might have in the future (many more resources than us etc.).

But I also do not have anywhere near the knowledge of @IngCr3at1on so am happy to divert to his recommendation here.

**Comment by IngCr3at1on** [comment]
@mitchellcash it's closer to how bitcoin was done yes (and how I originally did it and spent forever trying to figure out why Command-Line RPC failed), put simply that comment there is there for a reason ;)

**Comment by mitchellcash** [comment]
Closed in favour of #386

**Pull request closed without merging**
