### PR TITLE
Translation updates / string updates

### PR DESCRIPTION
**Pull request by mitchellcash**
- Split translation of RPC console welcome message and remove the need to take care of HTML br
- Remove some spaces in strings

### CODE REVIEW

**Comment by mitchellcash** [comment]
Slowly getting there with all this translation work :) Unneeded spaces and HTML code don't bode well with the translations.

**Comment by IngCr3at1on** [comment]
Aren't most of those spaces more for formatting vs "unneeded"?

**Comment by mitchellcash** [comment]
I would argue they're unneeded plus they can be annoying for translators. I would rather keep it standard sentence structure with a single space following a full stop.

**Comment by IngCr3at1on** [comment]
The full stops I agree but in the case of a colon followed by a blank space, that's padding so that whatever is being stuck after that colon is not right up against it. Personally I'd prefer it that way in most cases.

**Comment by mitchellcash** [comment]
Right sorry. The blank space after the colon is definitely unneeded. The Qt code handles the spacing and columns itself so we don't need to add our own additional spaces as they have no affect in this particular case.

**Comment by IngCr3at1on** [comment]
Got it, cool.

**Pull request merged**
