### PR TITLE
Split synchronization mechanisms from util.{h,cpp}

### PR DESCRIPTION
**Pull request by mitchellcash**
Reference:
https://github.com/bitcoin/bitcoin/commit/7f3ccb59da31c7b1706ebfbb401910923221f076

### CODE REVIEW

**Comment by PaycoinMaster** [comment]
Has anyone tested this?

**Comment by mitchellcash** [comment]
I know I have, but I would like if someone else could. At this stage I guess @IngCr3at1on can you help?

**Comment by IngCr3at1on** [comment]
This functions fine in my tests I vote merge.

**Comment by IngCr3at1on** [comment]
Actually hold off a bit either this or #136 has broken partly through a sync (I really doubt it's 136)

**Comment by IngCr3at1on** [comment]
My bad... the error I was encountering was in testing #136 and it's in relation to the issue addressed in #138. This can be merged imho.

**Comment by mitchellcash** [comment]
Thanks @IngCr3at1on. I was going to say I didn't come into this bug and I really doubted it was #136!

**Pull request merged**
