### PR TITLE
Add support for opening paycoin: URIs directly.

### PR DESCRIPTION
**Pull request by mitchellcash**
@IngCr3at1on it's finally done and testing on Windows is finally working. To be honest I should have kept looking into this when I started a few months ago and I could have had it done then but I got distracted with other things.

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
Just for curiosity was it that one check that I pointed out?

**Comment by IngCr3at1on** [comment]
qtipcserver.h still uses has  `#define BITCOINURI_QUEUE_NAME "BitcoinURI"` let's change that if possible.

**Comment by mitchellcash** [comment]
@IngCr3at1on I overlooked removing one of the `#if !defined(MAC_OSX) && !defined(WIN32)` lines. It frustrates me I stopped looking at this because all I had to do was remove that line and it could have solved all my problems months ago.

In regards to renaming `BitcoinURI` I'm happy to do that. Before I do this though would you also like me to go through the codebase and replace `parseBitcoinURI` with `parsePaycoinURI` etc.

**Comment by IngCr3at1on** [comment]
That's the check I was talking about :P

No, variable and function names are fine it's the actual defined value that concerns me.

**Comment by mitchellcash** [comment]
@IngCr3at1on it was to, thank you!

Alright changed the defined value to `PaycoinURI` and rebased over master.

**Comment by mitchellcash** [comment]
Rebased over master (plus I wanted Travis to run his eyes over it ;) )

**Comment by ligerzero459** [comment]
Just tested this on Windows and ran into two issues. First, if Paycoin hadn't started yet, it started it properly, but then dumped at the Overview tab and the address from the URI isn't anywhere to be found. But if the wallet was already open, it attempted to start a new instance instead of using the one already launched.

**Comment by mitchellcash** [comment]
@ligerzero459 damn I thought I had squashed those bugs. Are using gitian to build the Windows executables?

**Comment by IngCr3at1on** [comment]
@mitchellcash yes that was compiled in gitian he used your branch specifically.

**Comment by mitchellcash** [comment]
Thanks. So when I build in mingw I got it working but then gitian keeps having the issue described above which I was also facing on gitian builds. I will need to investigate further but if any of you doing gitian builds could also assist it would be much appreciated.

**Comment by IngCr3at1on** [comment]
I'm just trying to figure out what the major difference would be.

**Comment by mitchellcash** [comment]
@IngCr3at1on sorry stop that investigation I got confused. So it was a gitian build I used and I'm testing it now and it works.

I'm using a 32-bit install though. @ligerzero459 what about you?

**Comment by ligerzero459** [comment]
So this is working. Turns out it didn't re-create my shortcut when I installed it, so it started the 0.3.3.0 version instead of the 0.3.3.1c version. When I clicked the URI, it tried to open the new version, which I thought was already open. Started the right version and it detected the paycoin URIs like a boss

**Comment by IngCr3at1on** [comment]
That's cool. I'm sure a lot of people would like this feature.

**Comment by mitchellcash** [comment]
Good stuff! Thanks for testing

**Comment by mitchellcash** [comment]
Just updated with some minor nits. No code changes. The three changes were:
https://github.com/PaycoinFoundation/paycoin/commit/ad0ef408b1140852e825dcd6d95d6ded048e0556
https://github.com/PaycoinFoundation/paycoin/commit/0f9c6a7cd24386f2f790cc47cc9cb5507922bdaa
https://github.com/PaycoinFoundation/paycoin/commit/0626d6aa46c28a57175f78c898a8b157cae8aa32

**Pull request merged**
