### PR TITLE
Update threading

### PR DESCRIPTION
**Pull request by IngCr3at1on**
Do NOT merge at this time | discuss

My initial attempts at updating threading apparently missed something (boost thread implementation), which caused compat for windows to fail. This resolves building for windows and appears to work properly in Linux.

This brings us slightly more in-line with Bitcoin not to mention it is a code cleanup because it removes the pthread_t typedef for windows.

This needs significantly more testing before it should be merged.

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
Has anyone messed with this (@mitchellcash or @PaycoinMaster)

**Comment by mitchellcash** [comment]
Not yet sorry. Let me get something up and running maybe today, if not weekend

**Comment by mitchellcash** [comment]
@IngCr3at1on I can't test building for windows but a test build on Ubuntu 14.04 server was fine. Will let it run for a few days.

**Comment by mitchellcash** [comment]
Have been running this for the past two days and have encountered no issues.

LGTM

**Comment by PaycoinMaster** [comment]
I will try to build it for windows and see how it fairs my self.

**Comment by IngCr3at1on** [comment]
Rebased and confirmed this does build in gitian.
@PaycoinMaster have you looked into this one at all on Windows?

**Pull request merged**
