### PR TITLE
Update version for release 0.3.1.0 + release notes

### PR DESCRIPTION
**Pull request by IngCr3at1on**
This requires PRs #173 and #174 (as they are in the release notes)

NO OTHER OPEN PRS HAVE BEEN ADDED TO THE RELEASE NOTES

After merge update release tag:

`git checkout master`
`git pull origin master`
`git tag v0.3.1.0` or `git tag -a v0.3.1.0` to annotate
`git push origin v0.3.1.0`

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
Yes... I'd like @mitchellcash to confirm this one as well before merge, even if it is simple I'd like to make sure I didn't miss anything.

**Comment by PaycoinMaster** [comment]
Waiting on @mitchellcash Please confirm

**Comment by jwrb** [comment]
This looks good @PaycoinMaster. Giving credit where it's due! Notes look good! LGTM! :+1:

**Comment by mitchellcash** [comment]
Again, thanks @jwrb. Sorry I didn't get a chance to test my work job has been crazy lately and haven't had the time!

**Pull request merged**
