### PR TITLE
Add "Copy Scrape Address" action to Receive Coins tab context menu

### PR DESCRIPTION
**Pull request by IngCr3at1on**

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
Tried adding a button also but I can't seem to make it work so this is the code WITHOUT the button requirements.

**Comment by mitchellcash** [comment]
@IngCr3at1on I've made the code work with a button if you want to cherry-pick my commit:
https://github.com/mitchellcash/paycoin/commit/5502b882d0357f45242d2cfc07f9ec60a4603139

It's sitting on this branch of mine:
https://github.com/mitchellcash/paycoin/tree/scrapes-qt-context-menu

Feel free to test, provide feedback.

**Comment by IngCr3at1on** [comment]
Done, thanks @mitchellcash 

I'm entirely confused cause so far as I can tell your code is identical to the code I had when I tried to make it work but whatever lol

**Comment by mitchellcash** [comment]
Haha yeah I thought you would have tried the same code. Thanks for pulling my commit in!

**Comment by IngCr3at1on** [comment]
So far as I'm aware this works in full on linux, @mitchellcash did you ever test it in windows?

**Comment by mitchellcash** [comment]
@IngCr3at1on tested this on Windows and it works as expected.

**Pull request merged**
