### PR TITLE
Split synchronization mechanisms from util.{h,cpp}

### PR DESCRIPTION
**Pull request by mitchellcash**
- Split synchronization mechanisms from util.{h,cpp}
  I think the various wrappers and utility code around synchronization mechanisms warrant a separate source file.

- Use boost::thread locking instead of interprocess
  It was noticed there was a boost/thread/* set of synchronisation primitives, separate from those in boost/interprocess/sync/*. Given that they do not need to cope with locks being in shared memory, they are different and simpler on some systems.

  This commit replaces all sync.{h,cpp} infrastructure by systems provided by boost/thread/*.

  So far, it seems to work well on Linux, OSX and BSD (the latter two required a workaround before, as the interprocess semaphores and condition variables used spinlocks - it seems the thread ones don't).

- Fix DEBUG_LOCKCONTENTION
  Didnt compile.

### CODE REVIEW

**Comment by mitchellcash** [comment]
Last time we tried this I think Gitian screwed up and wouldn't compile. I'm hoping ce3333d helps with this (I'm not sure what caused the issue the first time around).

Because this did cause issues in attempt 1 this will need testing in Gitian and run a Windows and hopefully a Mac OS X build to ensure nothing breaks.

A simple `qmake` and `make` with a full sync on Ubuntu has been running fine for me.

**Comment by IngCr3at1on** [comment]
Yeah I could have told you this was still going to break when I looked at it cause nothing in those commits has anything to do with the actual error.

Ran a gitian build anyway: linux compiles fine, windows fails:

x86_64-w64-mingw32-g++ -c -frandom-seed=paycoin -O2 -frtti -fexceptions -Wall -Wextra -Wformat -Wformat-security -Wno-invalid-offsetof -Wno-sign-compare -Wno-unused-parameter -fdiagnostics-show-option -DBOOST_THREAD_USE_LIB -DQT_GUI -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -DUSE_IPV6 -DUSE_QRCODE -DUSE_UPNP=1 -DSTATICLIB -DBITCOIN_NEED_QT_PLUGINS -DHAVE_BUILD_INFO -DWIN32 -D_MT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_THREAD_SUPPORT -DQT_NEEDS_QMAIN -I'../../staging64/include/QtCore' -I'../../staging64/include/QtGui' -I'../../staging64/include' -I'../../staging64' -I'src' -I'src/json' -I'src/qt' -I'../../staging64/include/ActiveQt' -I'build' -I'build' -I'../../staging64/mkspecs/win32-g++' -o build/bitcoingui.o src/qt/bitcoingui.cpp
In file included from src/bignum.h:12:0,
                 from src/main.h:10,
                 from src/wallet.h:10,
                 from src/qt/bitcoingui.cpp:31:
src/util.h:173:57: error: ‘pid_t’ has not been declared
In file included from src/bignum.h:12:0,
                 from src/main.h:10,
                 from src/wallet.h:10,
                 from src/init.h:8,
                 from src/qt/bitcoin.cpp:13:
src/util.h:173:57: error: ‘pid_t’ has not been declared
In file included from ../../staging64/include/boost/thread/shared_mutex.hpp:18:0,
                 from ../../staging64/include/boost/thread/detail/thread_group.hpp:9,
                 from ../../staging64/include/boost/thread/thread.hpp:13,
                 from ../../staging64/include/boost/thread.hpp:13,
                 from src/util.h:25,
                 from src/bignum.h:12,
                 from src/main.h:10,
                 from src/wallet.h:10,
                 from src/qt/bitcoingui.cpp:31:

**Comment by mitchellcash** [comment]
I can't remember if I ever saw the error messages this was causing in Gitian last time this happened. Although I am getting the feeling you might prove me wrong here.

I will take a look now. Appreciate any help/time you can give to this as the man with the Gitian builder :)

**Comment by IngCr3at1on** [comment]
@mitchellcash this is the same issue we were originally getting that I spent 2 days trying to figure out what was going on, no clue :P

**Comment by mitchellcash** [comment]
Ahh yes I recall now. I knew you would prove me wrong.

Can you please take a look at: https://github.com/mitchellcash/paycoin/tree/splitsync-dev

**Comment by IngCr3at1on** [comment]
Ahha, that makes sense! LOL, yes that builds in gitian.

**Comment by mitchellcash** [comment]
As per above I have now added commit edcecdf which will solve the build problems for Windows

**Comment by scroogemcdev** [comment]
Needs rebase

**Comment by mitchellcash** [comment]
@scroogemcdev rebased and ready to go :)

**Pull request merged**
