### PR TITLE
Add new utility functions FileCommit(), RenameOver()

### PR DESCRIPTION
**Pull request by IngCr3at1on**
These will be required by later commits as we backport more bitcoin functionality over to paycoin.

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
I've only tested this on Linux, if someone wants to give windows a shot that would be awesome.

**Comment by IngCr3at1on** [comment]
Confirmed this builds in gitian but I haven't ran a windows build (have builds if someone would like to test them, reference 0.3.0.3u)

**Comment by mitchellcash** [comment]
Awesome. I'll make some Windows builds and test.

**Comment by IngCr3at1on** [comment]
Now that the release commits are all merged and gitian builds are done can we get this merged as I have other PRs staged that require it. @PaycoinMaster

**Comment by mitchellcash** [comment]
@PaycoinMaster testing is confirmed fine as well.

**Pull request merged**
