### PR TITLE
Primenode better db encapsulation

### PR DESCRIPTION
**Pull request by IngCr3at1on**
This requires #255 (will conflict)...

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
This has been rebased over master, it's fairly trivial but I'd like to have someone else test it anyway.

**Comment by mitchellcash** [comment]
Testing this now. Is there anything in particular you want me to look for otherwise I'll just let it run for the next few days.

**Comment by IngCr3at1on** [comment]
@mitchellcash main thing is that it accepts new blocks (both prime and normal)

**Comment by mitchellcash** [comment]
So far it looks good then :) running for over 2 days.

**Comment by IngCr3at1on** [comment]
This has been rebased over master

**Pull request merged**
