### PR TITLE
[not finished] Rework Network Stack, Rewrite Init, Implement Tor

### PR DESCRIPTION
**Pull request by jwrb**
Adds support for running as and connecting to Tor hidden services. *.onion addresses are mapped into the IPv6 range in the same way as OnionCat does.

See doc/Tor.txt for more information.

Taken from [pull #1174](https://github.com/bitcoin/bitcoin/pull/1174)

### CODE REVIEW

**Comment by jwrb** [comment]
This needs some edits before it's merged, as it throws some errors upon compilation.

**Comment by mitchellcash** [comment]
Have you also been able to test this? I can see if I can get a onion node up and running if you need?

**Comment by IngCr3at1on** [comment]
@mitchellcash I spoke to @jwrb last night, he did not get to test this in detail.

**Comment by IngCr3at1on** [comment]
Just a general note, it's best if each commit is build-able (in order of course), so probably be best to go back and start with what's needed first.

**Comment by jwrb** [comment]
Yeah, I'll close this down and go individual. Although we've got some changed (but not all) this implements. So it'll be a difficult call to get working

**Comment by IngCr3at1on** [comment]
@jwrb yeah I know we have some of this stuff at least in part, previous devs liked to take only parts of features instead of all of them.

**Pull request closed without merging**
