### PR TITLE
Add key shortcuts for RPC console tabs

### PR DESCRIPTION
**Pull request by mitchellcash**
- Alt-I for Information, Alt-C for Console

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
This isn't working on my arch box (haven't tested it on anything else yet). Code looks like it's missing something to me.

**Comment by mitchellcash** [comment]
Strange, it is working fine for me on Ubuntu. Admittedly no Mac or Windows tests have been performed, I was hoping someone else was able to do that. If not I can give building a Mac and Windows binary a go.

I referenced this Bitcoin commit: https://github.com/bitcoin/bitcoin/commit/bfbfb53ed468734376039f74a8ca2ddf2047c6f4

**Comment by mitchellcash** [comment]
Thanks @IngCr3at1on for creating some non-release builds of this branch for me to test.

I can now confirm this works on Linux 32-bit & 64-bit builds and Windows 32-bit & 64-bit. I didn't have a Mac build to test with but I think we can assume this is working. @IngCr3at1on did you get a chance to also confirm this commit works, in case others want a second source?

I think, as you said on Slack, the issue you had above might be isolated to your Arch setup.

**Comment by IngCr3at1on** [comment]
Aye @mitchellcash if it's working on Ubuntu it's likely something related to my config/setup. I have not tested it on another machine yet.

**Comment by mitchellcash** [comment]
No worries, unless anyone else wanted to test it I think we can safely merge this.

**Pull request merged**
