### PR TITLE
Replace instances of lld/llu with the PRI64d/PRI64u macro for MSVC++ compat

### PR DESCRIPTION
**Pull request by IngCr3at1on**

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
I'm sure there are other things that will stop MSVC++ from compiling but it's best to use the defined macros in this instance either way.

**Comment by IngCr3at1on** [comment]
This has been rebased over master. I'd like to confirm it doesn't somehow effect mingw compiling (@mitchellcash)  before merging and I'm still curious if it helps with MSVC++ compiling (though I expect many other errors will occur).

**Comment by mitchellcash** [comment]
mingw compiling is fine :) can't comment on MSVC++

**Comment by IngCr3at1on** [comment]
@mitchellcash someone surely will test MSVC++ eventually, either way I'm in favor of using the macro instead of lld. Just going to double check if I missed any instances of it lol.

**Pull request merged**
