### PR TITLE
Add Transifex support

### PR DESCRIPTION
**Pull request by mitchellcash**
- Add support for completing translations through Transifex (https://www.transifex.com/paycoin/paycoin/)
- Add a script to fetch and postprocess translations
- Full translation update with the new script

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
Nice, I'll have to play with this one a bit.

**Comment by mitchellcash** [comment]
I spent some good time mucking around with all of this so hopefully it should be sane. 

Let me know if you have any questions. I can also make you a maintainer on the Transifex repo as well if you want. But try not to break anything I spent ages figuring it all out haha. They have their own cli commands. 

    tx pull
    tx push -s --language=zh_CN
    Etc.

But I should be able to fix anything that goes wrong it can just be annoying. But if you are only interested in pulling translations from their with the script or cli being a maintainer or not wont stop you.

**Comment by mitchellcash** [comment]
Added a commit updating README.md with a brief overview of the new translation process.

**Comment by mitchellcash** [comment]
@IngCr3at1on have you had a chance to look at this one?

**Comment by IngCr3at1on** [comment]
@mitchellcash no sorry

**Comment by IngCr3at1on** [comment]
What am I missing?

Traceback (most recent call last):
  File "contrib/devtools/update-translations.py", line 185, in <module>
    fetch_all_translations()
  File "contrib/devtools/update-translations.py", line 41, in fetch_all_translations
    if subprocess.call([TX, 'pull', '-f']):
  File "/usr/lib/python3.5/subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1540, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'tx'

**Comment by mitchellcash** [comment]
Did you checkout my branch and run it from the root paycoin folder?

**Comment by IngCr3at1on** [comment]
Yep :P

**Comment by mitchellcash** [comment]
Hmm works for me 
```
MacBook-Pro:paycoin mitchellcash$ python contrib/devtools/update-translations.py
Pulling translations for resource paycoin.qt-translation-03x (source: src/qt/locale/paycoin_en.ts)
 -> sk_SK: src/qt/locale/paycoin_sk_SK.ts
 -> et_EE: src/qt/locale/paycoin_et_EE.ts
 -> cs: src/qt/locale/paycoin_cs.ts
 -> ar: src/qt/locale/paycoin_ar.ts
```
it goes on but that snippet should be enough.

Have you done this http://docs.transifex.com/client/setup/

**Comment by IngCr3at1on** [comment]
Nope, hadn't lol. Might I just say the transifex security methods are terribad. Make sure you set your .transifexrc to 700 for permissions ;)

**Comment by mitchellcash** [comment]
Haha yep! Annoying that it is probably the best tool out there though. Let's get some translating happening!

**Pull request merged**
