### PR TITLE
Get rid of snprintf (except one) with fixed buffers, shorten code

### PR DESCRIPTION
**Pull request by IngCr3at1on**
- Use strprintf or vstrprintf instead of snprintf

reference: https://github.com/bitcoin/bitcoin/pull/1302

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
While parts of this effect all OS the major changes are related to windows handling and has not been tested on my end.

**Comment by mitchellcash** [comment]
I'll make a Windows test build and run it for a couple of days

**Comment by IngCr3at1on** [comment]
@mitchellcash did you ever run that test build?

**Comment by mitchellcash** [comment]
I did and it looks good to me.

**Pull request merged**
