### PR TITLE
New splash screen

### PR DESCRIPTION
**Pull request by mitchellcash**
- New splash screen gives the user infos about the running client.
- New splash screen can handle long messages (in a lot of - languages the text is cropped in current release)
- Slightly adjusted size
- Contains textual information about the client
- Textinfos are dynamically written to the pixmap

When -testnet is switched on, the splashscreen will show the Paycoin logo with a testnet background color (as well as a text [testnet])

Example: https://dl.dropboxusercontent.com/u/37902134/Screen1.png
Testnet Example: https://dl.dropboxusercontent.com/u/37902134/Screen2.png

### CODE REVIEW

**Comment by PaycoinMaster** [comment]
Can more people comment on this to see if you would like me to pull this into the code line.

**Comment by BoXHocK** [comment]
I want this. It looks cool

**Comment by itsVictorVargas** [comment]
This splash screen looks awesome!

**Comment by IngCr3at1on** [comment]
I need to test the code but in respect to the images.

The testnet icon in resources is green but the splash you've provided is some other color the name of which I'm not sure (personally I like it more than the green lol).

We need some consistency @PaycoinMaster, @xmk3 and @jwrb has a testnet color scheme ever been discussed in the branding guidelines?

**Comment by mitchellcash** [comment]
The branding guidelines only showed a proposed colour for what I used as the mainnet splash. What I did for the testnet splash was just the exact opposite colour on the spectrum. I avoided green because that's what Bitcoin uses. I'm just on my phone but I can provide more info like colour codes after work tonight

**Comment by IngCr3at1on** [comment]
I can confirm this builds and runs properly.

**Comment by PaycoinMaster** [comment]
I have tested this on Windows. I am going to Merge this.

**Pull request merged**
