### PR TITLE
Move help messages out of AppInit2

### PR DESCRIPTION
**Pull request by IngCr3at1on**
- Removes \t's from help message that are removed afterwards anyway
- Moves UI-specific command-line options help to UI code
- Moves "-detachdb" out of #ifdef USE_UPNP

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
Fixed my typo in the commit message...

**Comment by IngCr3at1on** [comment]
Fixed the part where I had inadvertently reverted boost::algorthim::istarts_with back to strncasecmp.

**Comment by IngCr3at1on** [comment]
This has been rebased over master

**Comment by mitchellcash** [comment]
LGTM. But are you sure you moved "-detachdb" out of #ifdef USE_UPNP?

**Comment by IngCr3at1on** [comment]
Well I had but that commit was redone at least once lol.. also it looks like I had restored part of the detachdb help info that was previously removed. Fixed.

**Pull request merged**
