### PR TITLE
Cleanup leftover docs from the Peerunity fork

### LINKED ISSUE #422: Clean up "testing"-folders
https://github.com/PaycoinFoundation/paycoin/tree/master/testing

I think there's some stuff herr that can be deleted. Also there are many occurences of Peercoin PPC

### PR DESCRIPTION
**Pull request by mitchellcash**
Fixes #422.

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
This has the only documentation of multisig to my knowledge.

**Comment by mitchellcash** [comment]
You might be right. Should we put this on the Paycoin Wiki instead?

**Comment by IngCr3at1on** [comment]
@mitchellcash might not be a bad idea yeah

**Comment by mitchellcash** [comment]
Just a quick transposing job but it should be what you're after http://xpy.wiki/index.php?title=Multisig

(15 minutes)

**Pull request merged**
