### PR TITLE
Rpc modules

### PR DESCRIPTION
**Pull request by IngCr3at1on**
Moves all rpc externs to bitcoinrpc.h
Adds JSONRPCError prototype to bitcoinrpc.h (vs externing where required)
Adds HexBits prototype to bitcoinrpc.h
Removes unused namespace declarations from rpcrawtransaction.cpp

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
Though this shouldn't have any issues I'd appreciate some thorough testing.

**Comment by jwrb** [comment]
I'll get onto testing this. I'll log what I test as I go so we can ensure all features work. I'd appreciate if someone else could verify this after I'm done though. Perhaps @mitchellcash could you take a look later too? More eyes are always better. This isn't a big change but it moves around a lot of stuff so has potential to break a few bits.

**Comment by jwrb** [comment]
I'm getting an error compiling this branch using @evanlucas's Mac Build script.
```
usr/local/Cellar/boost/1.58.0/include/boost/type_traits/detail/has_binary_operator.hp:50: Parse error at "BOOST_JOIN"
make: *** [build/rpcconsole.moc] Error 1
make: *** Waiting for unfinished jobs....
                       make : failed
```

**Comment by jwrb** [comment]
This compiles fine as a daemon. Qt issues?

**Comment by jwrb** [comment]
I have tested the following RPC calls with this PR.
```
getblockcount
getdifficulty
getblock
getblockhash
settxfee
getcheckpoint
getrawmempool

dumpprivkey
importprivkey

getconnectioncount
getpeerinfo
sendalert

getrawtransaction
listunspent
createrawtransaction
decoderawtransaction
signrawtransaction
sendrawtransaction

getinfo
getnewaddress
getaccountaddress
setaccount
getaccount
getaddressesbyaccount
sendtoaddress
getreceivedbyaddress
getreceivedbyaccount
listminting
listreceivedbyaddress
listreceivedbyaccount
backupwallet
keypoolrefill
walletpassphrase
walletpassphrasechange
walletlock
encryptwallet
validateaddress
move
getbalance
sendfrom
sendmany
addmultisigaddress
createmultisig
gettransaction
listtransactions
signmessage
verifymessage
listaccounts
listsinceblock
listaddressbook

reservebalance
checkwallet
repairwallet
makekeypair
clearorphans
listmicroprimedata

setscrapeaddress
getscrapeaddress
listscrapeaddresses
deletescrapeaddress
```

All work as expected and the wallet functions normally. Commands return data to answer queries.

**Comment by jwrb** [comment]
Still can't compile the full QT. Daemon works fine though

**Comment by jwrb** [comment]
Tested with Boost 1.59. Still doesn't compile.

**Comment by jwrb** [comment]
Lots of swapping around as per our discussions and it still does not function correctly

**Comment by jwrb** [comment]
After much playing and talking with @IngCr3at1on. We found a simple way to fix this issue. Turns out Boost on Mac has some issues. This is only on Mac. (Boost 1.59, Qt 4.8.7)

The fix is wrapping part of the `util.h` boost headers with an if clause. Skipping them on moc generation.


```c
#ifndef Q_MOC_RUN
#include <boost/thread.hpp>
#include <boost/filesystem.hpp>
#include <boost/filesystem/path.hpp>
#include <boost/interprocess/sync/interprocess_recursive_mutex.hpp>
#include <boost/interprocess/sync/scoped_lock.hpp>
#include <boost/interprocess/sync/interprocess_semaphore.hpp>
#include <boost/interprocess/sync/lock_options.hpp>
#include <boost/date_time/gregorian/gregorian_types.hpp>
#include <boost/date_time/posix_time/posix_time_types.hpp>
#endif
```

This fixes compilation issues with the fork. Once this is changed this branch is ready to be merged in :)

**Comment by jwrb** [comment]
LGTM :+1:

**Comment by jwrb** [comment]
It'd be good if a few others running OSX could also check this over. @ligerzero459

**Comment by ligerzero459** [comment]
Compiles and runs on OS X :+1:

**Comment by jwrb** [comment]
Thanks a bunch @ligerzero459! LGTM!

**Pull request merged**
