### PR TITLE
Fix windows build

### PR DESCRIPTION
**Pull request by IngCr3at1on**
Revert the commits causing errors with gitian because I spent all of yesterday trying to fix it.

We will revisit this at a later time after compat has been cleaned up more.

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
I'd like to get this merged so I can better test those other PRs in gitian.

**Comment by mitchellcash** [comment]
Agreed. Sorry about introducing this I spoke with @IngCr3at1on a little bit yesterday on possible fixes but ended up on just reverting and revisiting this later

**Comment by mitchellcash** [comment]
@IngCr3at1on you didn't get any further in working this out did you? I'd love to get this back into the codebase at some point.

**Comment by IngCr3at1on** [comment]
Nope, fraid not

**Pull request merged**
