### PR TITLE
Add a menu option to edit config file.

### PR DESCRIPTION
**Pull request by IngCr3at1on**
Should open the configuration file in the default text editor for the machine.
Note this has only been tested in Linux.
Addresses #328

### CODE REVIEW

**Comment by jwrb** [comment]
This doesn't seem to open an editor for me. (OSX 10.10.5). I'll look into this further shortly

**Comment by IngCr3at1on** [comment]
@jwrb most likely that's cause there is no system default editor for .conf files.

**Comment by jwrb** [comment]
Double clicking config files opens them up just fine. Using the `open` command in terminal also works as expected (opening the files in sublime text)

```bash
 open ~/Library/Application\ Support/Paycoin/paycoin.conf 
```
Works just fine. So I'm not sure this is a system issue. More the way it's implemented?

**Comment by jwrb** [comment]
Why did this also get merged? Didn't we merge #409 which is the same?

**Comment by mitchellcash** [comment]
Hmm yes it shouldn't have been merged but because the two commit IDs are identical to the ones in #409 it actually had no ill effect.

**Comment by IngCr3at1on** [comment]
@jwrb aye that was my bad but as @mitchellcash said they're identical so no ill effect... Either way, oops.

**Pull request merged**
