### PR TITLE
Better validity checks for scrape addresses

### PR DESCRIPTION
**Pull request by IngCr3at1on**
Check IsValid on all address instances instead of jumping to IsMine;
	provides clearer error information

Return error codes for scrape addresses;
	used -1 for most, is for misc error

Check if a wallet is encrypted and if it's locked when making changes
to the scrapes database.

Add full tests for rpc scrape functionality.

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
This is a bug because currently a user can modify a scrape address on a locked wallet without authentication.

This requires #315 for the tests to run.

**Comment by IngCr3at1on** [comment]
This has been rebased over master and added a commit to remove a now-unneeded extern (can be squashed after review).

**Comment by mitchellcash** [comment]
Confirmed testing in both the Qt and also paycoind with RPC calls. Everything looks good to me.

**Comment by scroogemcdev** [comment]
Rebased over master to accommodate #421

**Comment by IngCr3at1on** [comment]
Rebased over master to accommodate #421

**Pull request merged**
