### PR TITLE
clear path cache after getting a proper config file

### PR DESCRIPTION
**Pull request by mitchellcash**
Fixes the below:

1. Create an empty data directory with a testnet paycoin.conf; e.g.
    mkdir /tmp/d
    echo "testnet=1" >> /tmp/d/paycoin.conf
    echo "rpcuser=abc" >> /tmp/d/paycoin.conf
    echo "rpcpassword=def" >> /tmp/d/paycoin.conf

2. Run Paycoin-Qt with -datadir=/tmp/d

You get a nice orange splashscreen, BUT a wallet.dat and blockchain files directly in /tmp/d, not in /tmp/d/testnet3/

paycoind behaves correctly.

Bitcoin reference:
https://github.com/bitcoin/bitcoin/commit/b357a71cfaf99dd2e7d203a12edfcc5df4a93386

### CODE REVIEW

**Comment by mitchellcash** [comment]
Label: `Bug`

**Comment by IngCr3at1on** [comment]
This doesn't occur in Linux, just for knowledge sake do you know if it happens on Mac or Windows or both?

**Comment by mitchellcash** [comment]
Hmm I'm embarrassed to admit I didn't actually test this one thinking it was a safe commit. I also can't reproduce this on Windows or Mac.

I still think it should be merged as it is still following the same code path as what Bitcoin did but it has no effect so up to everyone.

**Comment by IngCr3at1on** [comment]
Hahaha... glad I'm not insane :P

It has no ill effect so far as I can tell so I've got no problem with it, changing the label though lol

**Pull request merged**
