### PR TITLE
add default value in -timout description

### PR DESCRIPTION
**Pull request by jwrb**
Taken from [#1761](https://github.com/bitcoin/bitcoin/pull/1761)

### CODE REVIEW

**Comment by mitchellcash** [comment]
The comment is against the wrong Bitcoin PR, it should say it's taken from https://github.com/bitcoin/bitcoin/pull/1761.

This is a trivial change and LGTM.

**Comment by jwrb** [comment]
Edited. Probably had the wrong one in my clipboard.

**Comment by IngCr3at1on** [comment]
Silly question... Did anyone confirm that is the valid timeout time?

**Comment by IngCr3at1on** [comment]
Confirmed the timeout in init.cpp, LGTM

**Pull request merged**
