### PR TITLE
[URGENT] Add owl background

### PR DESCRIPTION
**Pull request by whitj00**
This is urgent.

I  know some people won't like this, but they can compile it themselves.

### CODE REVIEW

**Comment by whitj00** [comment]
@xmk3 says veto, and I decide to veto the veto

Viva la revolution

**Comment by IngCr3at1on** [comment]
Am I the only one reminded of Futurama?

"We're owl exterminators."
"Then exterminate this owl!"

I'm going to have to agree with @xmk3, I say no :P

**Comment by BoXHocK** [comment]
I give this +1

**Comment by korfax** [comment]
I love it! Owl Coin.

**Comment by korfax** [comment]
TeamOWL

**Comment by korfax** [comment]
Owl coin will rise from the ashes.

**Comment by PaycoinMaster** [comment]
Closing this.

**Pull request closed without merging**
