### PR TITLE
Script to be able to perform copyright header updates

### PR DESCRIPTION
**Pull request by mitchellcash**
Referenced from https://github.com/bitcoin/bitcoin/commit/57702541a2009d4b936ebfddeeec3db7f8f74e5c

Original author @gubatron

This is being put here for future use as no current files were modified when using the script.

### CODE REVIEW

**Comment by gubatron** [comment]
ha, good to know this is in use :) cheers.

**Comment by IngCr3at1on** [comment]
Interesting

**Comment by IngCr3at1on** [comment]
The real question on this is if anyone will be using the script enough for it to need to be present.

**Comment by mitchellcash** [comment]
It will come in handy come 2016 and seeing as it's going into the devtools folder and not burdening the actual Paycoin core codebase I see no harm in leaving it in devtools for possible future use. It's a useful script and if needed come 2016 I'll make sure to use it ;)

**Pull request merged**
