### PR TITLE
Changes to optionsdialog.cpp

### PR DESCRIPTION
**Pull request by mitchellcash**
- Rename "Start Paycoin on window system startup" to "Start Paycoin on system login" and move it to Main
- Hide "Window" Options on Mac as there are currently none available
- Add Alt-Shortcuts where they were missing
- Allow translation of "default"

Reference:
https://github.com/bitcoin/bitcoin/commit/81c45c0a94d10717f105d28f6d13bac0714d111c

### CODE REVIEW

**Comment by IngCr3at1on** [comment]
Seems to work, obviously I haven't tested the start on login or the removal of the Mac options

**Comment by mitchellcash** [comment]
I've tested everything but the Mac stuff as I still haven't got Mac builds working. Of course this is me testing my own commit so another tester would be appreciated.

**Comment by scroogemcdev** [comment]
@HyperCommNet can you check the mac functionality on this?

**Comment by jwrb** [comment]
I'll be working on this shortly. Testing in a moment

**Comment by jwrb** [comment]
This is based upon 3.2.0. This needs to be rebased over master for proper testing.

**Comment by jwrb** [comment]
Rebased and testing locally.

**Comment by jwrb** [comment]
Works as expected! :) Functions run fine and it's good! LGTM +1

**Pull request merged**
